name: Dev Build

on:
  workflow_dispatch:
  push:
    branches:    
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup node and npm
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm Dependencies
      working-directory: Source/TurnTracker.Client
      run: npm install
      
    - name: Install angular CLI
      run: npm install -g @angular/cli
      
    - name: Build with npm
      working-directory: Source/TurnTracker.Client
      run: npm run-script build
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
